services:
  db:
    image: mysql:8.0
    container_name: DBMS_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/schemas/docker-init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7-alpine
    container_name: DBMS_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mysql_data:
  