import { PLACEHOLDER_UUID } from "./fixtures.js";

const U = PLACEHOLDER_UUID;

/**
 * @typedef {object} RouteEntry
 * @property {string} method
 * @property {string} path
 * @property {boolean} [public]
 * @property {string[]} [permissions]
 * @property {string[]} [anyPermissions]
 * @property {string[]} [roles]
 * @property {'citizen'|'dispatcher'|'agencyRep'} [denyPersona] - persona that should receive 403
 * @property {boolean} [hasBodyValidator]
 * @property {'citizen'|'dispatcher'|'systemAdmin'|'agencyRep'} [validationPersona]
 * @property {boolean} [agencyRouter]
 */

/** @type {RouteEntry[]} */
export const ROUTE_MANIFEST = [
  { method: "GET", path: "/health", public: true },

  { method: "POST", path: "/auth/register", public: true, hasBodyValidator: true },
  { method: "POST", path: "/auth/login", public: true, hasBodyValidator: true },
  { method: "POST", path: "/auth/refresh", public: true, hasBodyValidator: true },

  { method: "GET", path: "/users/me" },
  {
    method: "POST",
    path: `/users/${U}/roles`,
    permissions: ["auth.manage_roles"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "systemAdmin",
  },

  { method: "POST", path: "/locations", hasBodyValidator: true, validationPersona: "citizen" },
  { method: "GET", path: "/locations/my", validationPersona: "citizen" },
  { method: "GET", path: "/locations/search", validationPersona: "citizen" },
  { method: "GET", path: "/locations/reverse", validationPersona: "citizen" },
  { method: "GET", path: `/locations/${U}`, validationPersona: "citizen" },

  { method: "GET", path: "/notifications/my", validationPersona: "citizen" },
  { method: "GET", path: "/notifications/my/unread-count", validationPersona: "citizen" },
  {
    method: "PATCH",
    path: "/notifications/1/read",
    hasBodyValidator: false,
    validationPersona: "citizen",
  },

  { method: "GET", path: "/intake/reports/my", validationPersona: "citizen" },
  { method: "GET", path: "/intake/reports/my/stats", validationPersona: "citizen" },
  { method: "GET", path: "/intake/reports/my/service-cases", validationPersona: "citizen" },
  { method: "GET", path: "/intake/reports/my/incidents", validationPersona: "citizen" },
  { method: "GET", path: `/intake/reports/${U}`, validationPersona: "citizen" },
  { method: "GET", path: `/intake/reports/${U}/reported-location-history`, validationPersona: "citizen" },
  {
    method: "PATCH",
    path: `/intake/reports/${U}/location`,
    hasBodyValidator: true,
    validationPersona: "citizen",
  },
  { method: "POST", path: "/intake/reports", hasBodyValidator: true, validationPersona: "citizen" },
  {
    method: "GET",
    path: `/intake/service-cases/${U}/messages`,
    validationPersona: "citizen",
  },
  {
    method: "POST",
    path: `/intake/service-cases/${U}/messages`,
    hasBodyValidator: true,
    validationPersona: "citizen",
  },
  {
    method: "POST",
    path: `/intake/reports/${U}/classify/service-case`,
    roles: ["dispatcher", "system_admin"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/intake/reports/${U}/classify/emergency`,
    roles: ["dispatcher", "system_admin"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/intake/reports/${U}/escalate`,
    roles: ["dispatcher", "system_admin"],
    permissions: ["case.escalate", "incident.create"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },

  {
    method: "GET",
    path: "/operations/dispatcher/overview",
    permissions: ["incident.classify"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: "/operations/intake-reports",
    permissions: ["incident.classify"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: `/operations/intake-reports/${U}`,
    permissions: ["incident.classify"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: `/operations/intake-reports/${U}/reported-location-history`,
    permissions: ["incident.classify"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/operations/intake-reports/${U}/promote/emergency`,
    permissions: ["incident.create", "incident.classify"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: "/operations/gateway/999/intake-and-incident",
    permissions: ["incident.classify"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: "/operations/incidents",
    permissions: ["incident.create"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: "/operations/incidents",
    anyPermissions: ["incident.create", "incident.update_status"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: `/operations/incidents/${U}`,
    anyPermissions: ["incident.create", "incident.update_status"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "PATCH",
    path: `/operations/incidents/${U}/status`,
    permissions: ["incident.update_status"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/operations/incidents/${U}/notes`,
    permissions: ["incident.update_status"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/operations/incidents/${U}/intake-reports`,
    anyPermissions: ["incident.create", "incident.update_status"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/operations/incidents/${U}/agencies`,
    permissions: ["incident.assign_agency"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: "/operations/units/available",
    permissions: ["dispatch.create"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/operations/incidents/${U}/dispatches`,
    permissions: ["dispatch.create"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "PATCH",
    path: `/operations/dispatches/${U}/status`,
    permissions: ["dispatch.update_status"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: "/operations/agencies/workload",
    anyPermissions: ["dispatch.create", "incident.assign_agency"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: `/operations/incidents/${U}/response-timing`,
    anyPermissions: ["dispatch.create", "incident.assign_agency"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: "/operations/service-cases",
    permissions: ["case.respond"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: `/operations/service-cases/${U}`,
    permissions: ["case.respond"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "GET",
    path: `/operations/service-cases/${U}/messages`,
    permissions: ["case.respond"],
    denyPersona: "citizen",
    validationPersona: "dispatcher",
  },
  {
    method: "PATCH",
    path: `/operations/service-cases/${U}/status`,
    permissions: ["case.respond"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/operations/service-cases/${U}/messages`,
    permissions: ["case.respond"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/operations/service-cases/${U}/assignments`,
    permissions: ["case.assign"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },
  {
    method: "POST",
    path: `/operations/service-cases/${U}/resolve`,
    permissions: ["case.respond"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "dispatcher",
  },

  {
    method: "POST",
    path: "/admin/agencies/onboard",
    permissions: ["agency.manage"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "systemAdmin",
  },
  {
    method: "GET",
    path: "/admin/agencies",
    permissions: ["agency.manage"],
    denyPersona: "citizen",
    validationPersona: "systemAdmin",
  },
  {
    method: "GET",
    path: `/admin/agencies/${U}`,
    permissions: ["agency.manage"],
    denyPersona: "citizen",
    validationPersona: "systemAdmin",
  },
  {
    method: "PATCH",
    path: `/admin/agencies/${U}`,
    permissions: ["agency.manage"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "systemAdmin",
  },
  {
    method: "PATCH",
    path: `/admin/agencies/${U}/deactivate`,
    permissions: ["agency.manage"],
    denyPersona: "citizen",
    validationPersona: "systemAdmin",
  },
  {
    method: "PATCH",
    path: `/admin/agencies/${U}/activate`,
    permissions: ["agency.manage"],
    denyPersona: "citizen",
    validationPersona: "systemAdmin",
  },
  {
    method: "POST",
    path: `/admin/agencies/${U}/representatives`,
    permissions: ["agency.manage"],
    denyPersona: "citizen",
    hasBodyValidator: true,
    validationPersona: "systemAdmin",
  },
  {
    method: "GET",
    path: `/admin/agencies/${U}/representatives`,
    permissions: ["agency.manage"],
    denyPersona: "citizen",
    validationPersona: "systemAdmin",
  },
  {
    method: "PATCH",
    path: `/admin/agency-memberships/${U}/deactivate`,
    permissions: ["agency.manage"],
    denyPersona: "citizen",
    validationPersona: "systemAdmin",
  },

  {
    method: "GET",
    path: "/agency/me",
    permissions: ["agency.view_own"],
    denyPersona: "citizen",
    agencyRouter: true,
    validationPersona: "agencyRep",
  },
  {
    method: "GET",
    path: "/agency/incidents",
    permissions: ["dispatch.view_own_agency"],
    denyPersona: "citizen",
    agencyRouter: true,
    validationPersona: "agencyRep",
  },
  {
    method: "GET",
    path: "/agency/dispatches",
    permissions: ["dispatch.view_own_agency"],
    denyPersona: "citizen",
    agencyRouter: true,
    validationPersona: "agencyRep",
  },
  {
    method: "PATCH",
    path: `/agency/dispatches/${U}/status`,
    permissions: ["dispatch.update_own_agency"],
    denyPersona: "citizen",
    agencyRouter: true,
    hasBodyValidator: true,
    validationPersona: "agencyRep",
  },
  {
    method: "GET",
    path: "/agency/units",
    permissions: ["agency.view_own"],
    denyPersona: "citizen",
    agencyRouter: true,
    validationPersona: "agencyRep",
  },
  {
    method: "POST",
    path: "/agency/units",
    permissions: ["agency.manage_own_units"],
    denyPersona: "citizen",
    agencyRouter: true,
    hasBodyValidator: true,
    validationPersona: "agencyRep",
  },
  {
    method: "PATCH",
    path: `/agency/units/${U}`,
    permissions: ["agency.manage_own_units"],
    denyPersona: "citizen",
    agencyRouter: true,
    validationPersona: "agencyRep",
  },
  {
    method: "PATCH",
    path: `/agency/units/${U}/deactivate`,
    permissions: ["agency.manage_own_units"],
    denyPersona: "citizen",
    agencyRouter: true,
    validationPersona: "agencyRep",
  },
  {
    method: "PATCH",
    path: `/agency/units/${U}/status`,
    permissions: ["agency.manage_own_units"],
    denyPersona: "citizen",
    agencyRouter: true,
    hasBodyValidator: true,
    validationPersona: "agencyRep",
  },
  {
    method: "GET",
    path: `/agency/incidents/${U}/response-logs`,
    permissions: ["dispatch.view_own_agency"],
    denyPersona: "citizen",
    agencyRouter: true,
    validationPersona: "agencyRep",
  },
  {
    method: "POST",
    path: `/agency/incidents/${U}/response-logs`,
    permissions: ["response_log.create_own_agency"],
    denyPersona: "citizen",
    agencyRouter: true,
    hasBodyValidator: true,
    validationPersona: "agencyRep",
  },
];

export const PROTECTED_ROUTES = ROUTE_MANIFEST.filter((r) => !r.public);
export const FORBIDDEN_ROUTES = ROUTE_MANIFEST.filter((r) => r.denyPersona);
export const VALIDATION_BODY_ROUTES = ROUTE_MANIFEST.filter((r) => r.hasBodyValidator);
export const PUBLIC_BODY_ROUTES = ROUTE_MANIFEST.filter((r) => r.public && r.hasBodyValidator);
