-- PostgreSQL / Supabase preamble (converted from 00_preamble.sql)
SET client_encoding = 'UTF8';
SET TIME ZONE 'UTC';


-- Required extensions for NIERS schema
CREATE EXTENSION IF NOT EXISTS postgis;


-- from 05_identity_rbac.sql
-- ============================================================
-- 1. Identity, Auth, RBAC
-- ============================================================



CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    account_status VARCHAR(64) CHECK (account_status IN ('active','suspended','disabled','pending_verification')) NOT NULL DEFAULT 'pending_verification',
    account_status_reason TEXT NULL,
    account_status_expires_at TIMESTAMP NULL,
    email_verified_at TIMESTAMP NULL,
    last_login_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_users_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_email_not_blank CHECK (CHAR_LENGTH(TRIM(email)) > 0)
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    is_system_role BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_roles_role_code UNIQUE (role_code), CONSTRAINT uq_roles_name UNIQUE (name),
    CONSTRAINT chk_roles_role_code_not_blank CHECK (CHAR_LENGTH(TRIM(role_code)) > 0),
    CONSTRAINT chk_roles_name_not_blank CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permission_code VARCHAR(150) NOT NULL,
    module_name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_permissions_permission_code UNIQUE (permission_code),
    CONSTRAINT chk_permissions_code_not_blank CHECK (CHAR_LENGTH(TRIM(permission_code)) > 0)
);
CREATE INDEX idx_permissions_module_name ON permissions (module_name);

CREATE TABLE role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_role_permissions_role_permission UNIQUE (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions (permission_id);

CREATE TABLE user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_by_user_id BIGINT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_user_roles_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_user_roles_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_user_roles_role_id ON user_roles (role_id);
CREATE INDEX idx_user_roles_assigned_by ON user_roles (assigned_by_user_id);

-- from 06_geography_and_service_zones.sql
-- Geography tables are created before user_profiles because profiles can reference locations.

-- ============================================================
-- 2. Geography and Locations
-- ============================================================



CREATE TABLE administrative_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_area_id BIGINT NULL,
    area_type VARCHAR(64) CHECK (area_type IN ('division','district','upazila','union','ward','area')) NOT NULL,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_administrative_areas_code UNIQUE (code), CONSTRAINT uq_administrative_areas_parent_type_name UNIQUE (parent_area_id, area_type, name),
    CONSTRAINT fk_administrative_areas_parent FOREIGN KEY (parent_area_id) REFERENCES administrative_areas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_administrative_areas_name_not_blank CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);
CREATE INDEX idx_administrative_areas_parent ON administrative_areas (parent_area_id);
CREATE INDEX idx_administrative_areas_type ON administrative_areas (area_type);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    admin_area_id BIGINT NULL,
    latitude DECIMAL(9,6) NOT NULL,
    longitude DECIMAL(9,6) NOT NULL,
    geo_point geography(POINT, 4326) NOT NULL,
    address_text VARCHAR(255) NOT NULL,
    place_name VARCHAR(150) NULL,
    source VARCHAR(64) CHECK (source IN ('user_shared','dispatcher_selected','api_geocoded','manual_entry')) NOT NULL,
    created_by_user_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_locations_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_locations_admin_area FOREIGN KEY (admin_area_id) REFERENCES administrative_areas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_locations_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_locations_latitude CHECK (latitude BETWEEN -90.000000 AND 90.000000),
    CONSTRAINT chk_locations_longitude CHECK (longitude BETWEEN -180.000000 AND 180.000000),
    CONSTRAINT chk_locations_address_not_blank CHECK (CHAR_LENGTH(TRIM(address_text)) > 0)
);
CREATE INDEX idx_locations_admin_area ON locations (admin_area_id);
CREATE INDEX idx_locations_created_by ON locations (created_by_user_id);
CREATE INDEX idx_locations_lat_lng ON locations (latitude, longitude);
CREATE INDEX idx_locations_geo_point ON locations USING GIST (geo_point);

CREATE TABLE user_profiles (
    user_id BIGINT NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    secondary_phone_number VARCHAR(30) NULL,
    preferred_language VARCHAR(64) CHECK (preferred_language IN ('bn','en')) NOT NULL DEFAULT 'bn',
    address_location_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_user_profiles_address_location FOREIGN KEY (address_location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_user_profiles_full_name_not_blank CHECK (CHAR_LENGTH(TRIM(full_name)) > 0)
);
CREATE INDEX idx_user_profiles_address_location ON user_profiles (address_location_id);

CREATE TABLE auth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    token_type VARCHAR(64) CHECK (token_type IN ('refresh','password_reset','email_verification')) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_auth_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_auth_tokens_expires_after_created CHECK (expires_at > created_at)
);
CREATE INDEX idx_auth_tokens_user_type ON auth_tokens (user_id, token_type);

CREATE TABLE service_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    zone_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_service_zones_zone_code UNIQUE (zone_code),
    CONSTRAINT chk_service_zones_name_not_blank CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);

CREATE TABLE service_zone_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    service_zone_id BIGINT NOT NULL,
    admin_area_id BIGINT NOT NULL,
    PRIMARY KEY (id), CONSTRAINT uq_service_zone_areas_zone_area UNIQUE (service_zone_id, admin_area_id),
    CONSTRAINT fk_service_zone_areas_zone FOREIGN KEY (service_zone_id) REFERENCES service_zones(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_service_zone_areas_admin_area FOREIGN KEY (admin_area_id) REFERENCES administrative_areas(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_service_zone_areas_admin_area ON service_zone_areas (admin_area_id);

CREATE TABLE saved_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    label VARCHAR(100) NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    PRIMARY KEY (id), CONSTRAINT uq_saved_locations_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_saved_locations_user_location_active UNIQUE (user_id, location_id, is_deleted),
    CONSTRAINT fk_saved_locations_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_saved_locations_location
        FOREIGN KEY (location_id) REFERENCES locations(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_saved_locations_user_active_created ON saved_locations (user_id, is_deleted, created_at);
CREATE INDEX idx_saved_locations_location ON saved_locations (location_id);

-- from 07_reports_intake_999.sql
-- ============================================================
-- 3. Reporter, Intake, and 999 Calls
-- ============================================================



CREATE TABLE reporter_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    linked_user_id BIGINT NULL,
    full_name VARCHAR(150) NULL,
    phone_number VARCHAR(30) NULL,
    email VARCHAR(255) NULL,
    is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_reporter_contacts_linked_user FOREIGN KEY (linked_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_reporter_contacts_linked_user ON reporter_contacts (linked_user_id);
CREATE INDEX idx_reporter_contacts_phone ON reporter_contacts (phone_number);

CREATE TABLE report_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel_code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_report_channels_channel_code UNIQUE (channel_code),
    CONSTRAINT chk_report_channels_name_not_blank CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);

CREATE TABLE report_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_category_id BIGINT NULL,
    category_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_report_categories_category_code UNIQUE (category_code),
    CONSTRAINT fk_report_categories_parent FOREIGN KEY (parent_category_id) REFERENCES report_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_report_categories_name_not_blank CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);
CREATE INDEX idx_report_categories_parent ON report_categories (parent_category_id);

CREATE TABLE intake_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_intake_statuses_status_code UNIQUE (status_code)
);

CREATE TABLE intake_status_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_status_id BIGINT NOT NULL,
    to_status_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_note BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id), CONSTRAINT uq_intake_status_transitions_from_to UNIQUE (from_status_id, to_status_id),
    CONSTRAINT fk_intake_status_transitions_from FOREIGN KEY (from_status_id) REFERENCES intake_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_intake_status_transitions_to FOREIGN KEY (to_status_id) REFERENCES intake_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_intake_status_transitions_to ON intake_status_transitions (to_status_id);

CREATE TABLE intake_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    report_code VARCHAR(60) NOT NULL,
    reporter_user_id BIGINT NULL,
    reporter_contact_id BIGINT NULL,
    channel_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    reported_location_id BIGINT NOT NULL,
    summary VARCHAR(255) NOT NULL,
    description TEXT NULL,
    current_status_id BIGINT NOT NULL,
    final_disposition VARCHAR(64) CHECK (final_disposition IN ('valid','duplicate','false_report','prank','insufficient_info','closed_without_action')) NULL,
    received_by_user_id BIGINT NULL,
    reported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_intake_reports_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_intake_reports_report_code UNIQUE (report_code),
    CONSTRAINT fk_intake_reports_reporter_user FOREIGN KEY (reporter_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_intake_reports_reporter_contact FOREIGN KEY (reporter_contact_id) REFERENCES reporter_contacts(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_intake_reports_channel FOREIGN KEY (channel_id) REFERENCES report_channels(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_intake_reports_category FOREIGN KEY (category_id) REFERENCES report_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_intake_reports_location FOREIGN KEY (reported_location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_intake_reports_received_by FOREIGN KEY (received_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_intake_reports_current_status FOREIGN KEY (current_status_id) REFERENCES intake_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_intake_reports_summary_not_blank CHECK (CHAR_LENGTH(TRIM(summary)) > 0),
    CONSTRAINT chk_intake_reports_reported_before_created CHECK (reported_at <= created_at)
);
CREATE INDEX idx_intake_reports_reporter_user ON intake_reports (reporter_user_id);
CREATE INDEX idx_intake_reports_reporter_contact ON intake_reports (reporter_contact_id);
CREATE INDEX idx_intake_reports_channel ON intake_reports (channel_id);
CREATE INDEX idx_intake_reports_category ON intake_reports (category_id);
CREATE INDEX idx_intake_reports_location ON intake_reports (reported_location_id);
CREATE INDEX idx_intake_reports_current_status ON intake_reports (current_status_id);
CREATE INDEX idx_intake_reports_reported_at ON intake_reports (reported_at);

CREATE TABLE intake_report_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    intake_report_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_irsh_report FOREIGN KEY (intake_report_id) REFERENCES intake_reports(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_irsh_status FOREIGN KEY (status_id) REFERENCES intake_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_irsh_changed_by FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_irsh_report_changed ON intake_report_status_history (intake_report_id, changed_at);
CREATE INDEX idx_irsh_status ON intake_report_status_history (status_id);
CREATE INDEX idx_irsh_changed_by ON intake_report_status_history (changed_by_user_id);

CREATE TABLE intake_report_location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    intake_report_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    previous_location_id BIGINT NULL,
    change_kind VARCHAR(64) CHECK (change_kind IN ('initial_create','location_patch')) NOT NULL,
    changed_by_user_id BIGINT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    change_reason VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_irlh_report FOREIGN KEY (intake_report_id) REFERENCES intake_reports(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_irlh_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_irlh_previous_location FOREIGN KEY (previous_location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_irlh_changed_by FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_irlh_report_changed ON intake_report_location_history (intake_report_id, changed_at);
CREATE INDEX idx_irlh_location ON intake_report_location_history (location_id);
CREATE INDEX idx_irlh_previous_location ON intake_report_location_history (previous_location_id);
CREATE INDEX idx_irlh_changed_by ON intake_report_location_history (changed_by_user_id);

CREATE TABLE intake_report_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    intake_report_id BIGINT NOT NULL,
    uploaded_by_user_id BIGINT NULL,
    file_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    mime_type VARCHAR(120) NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_ira_report FOREIGN KEY (intake_report_id) REFERENCES intake_reports(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_ira_uploaded_by FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_ira_storage_key_not_blank CHECK (CHAR_LENGTH(TRIM(storage_key)) > 0)
);
CREATE INDEX idx_intake_report_attachments_report ON intake_report_attachments (intake_report_id);
CREATE INDEX idx_intake_report_attachments_user ON intake_report_attachments (uploaded_by_user_id);

CREATE TABLE emergency_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    intake_report_id BIGINT NOT NULL,
    dispatcher_id BIGINT NOT NULL,
    caller_phone_number VARCHAR(30) NULL,
    call_started_at TIMESTAMP NOT NULL,
    call_ended_at TIMESTAMP NULL,
    triaged_at TIMESTAMP NULL,
    call_status VARCHAR(64) CHECK (call_status IN ('received','triaged','linked_to_incident','transferred','closed','dropped','false_alarm')) NOT NULL DEFAULT 'received',
    recording_url VARCHAR(500) NULL,
    transcript_text TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_emergency_calls_intake_report UNIQUE (intake_report_id),
    CONSTRAINT fk_emergency_calls_intake_report FOREIGN KEY (intake_report_id) REFERENCES intake_reports(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_emergency_calls_dispatcher FOREIGN KEY (dispatcher_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_emergency_calls_end_after_start CHECK (call_ended_at IS NULL OR call_ended_at >= call_started_at),
    CONSTRAINT chk_emergency_calls_triaged_after_start CHECK (triaged_at IS NULL OR triaged_at >= call_started_at)
);
CREATE INDEX idx_emergency_calls_dispatcher ON emergency_calls (dispatcher_id);
CREATE INDEX idx_emergency_calls_started ON emergency_calls (call_started_at);
CREATE INDEX idx_emergency_calls_status ON emergency_calls (call_status);

CREATE TABLE emergency_call_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    emergency_call_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    note_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_call_notes_call FOREIGN KEY (emergency_call_id) REFERENCES emergency_calls(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_call_notes_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_call_notes_text_not_blank CHECK (CHAR_LENGTH(TRIM(note_text)) > 0)
);
CREATE INDEX idx_call_notes_call ON emergency_call_notes (emergency_call_id);
CREATE INDEX idx_call_notes_user ON emergency_call_notes (created_by_user_id);

CREATE TABLE emergency_call_triage_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    emergency_call_id BIGINT NOT NULL,
    question_text VARCHAR(500) NOT NULL,
    answer_text TEXT NULL,
    answered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_triage_answers_call FOREIGN KEY (emergency_call_id) REFERENCES emergency_calls(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_triage_question_not_blank CHECK (CHAR_LENGTH(TRIM(question_text)) > 0)
);
CREATE INDEX idx_triage_answers_call ON emergency_call_triage_answers (emergency_call_id);

-- from 07b_intake_verification_reporter_actions.sql
-- ============================================================
-- Intake report verification reviews and reporter account actions
-- ============================================================



CREATE TABLE intake_report_verification_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    intake_report_id BIGINT NOT NULL,
    reviewed_by_user_id BIGINT NOT NULL,
    verdict VARCHAR(40) NOT NULL,
    reason VARCHAR(255) NULL,
    evidence_note TEXT NULL,
    confidence_level VARCHAR(20) NOT NULL DEFAULT 'medium',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id), CONSTRAINT uq_intake_report_verification_reviews_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_intake_report_verification_reviews_intake_report
        FOREIGN KEY (intake_report_id) REFERENCES intake_reports(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_intake_report_verification_reviews_reviewed_by
        FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_intake_report_verification_reviews_verdict CHECK (
        verdict IN (
            'genuine',
            'duplicate',
            'mistaken',
            'unverified',
            'false_alarm',
            'malicious_false_report'
        )
    ),
    CONSTRAINT chk_intake_report_verification_reviews_confidence CHECK (
        confidence_level IN ('low', 'medium', 'high')
    )
);
CREATE INDEX idx_intake_report_verification_reviews_intake_report ON intake_report_verification_reviews (intake_report_id);
CREATE INDEX idx_intake_report_verification_reviews_reviewed_by ON intake_report_verification_reviews (reviewed_by_user_id);
CREATE INDEX idx_intake_report_verification_reviews_verdict ON intake_report_verification_reviews (verdict);
CREATE INDEX idx_intake_report_verification_reviews_created_at ON intake_report_verification_reviews (created_at);

CREATE TABLE reporter_account_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    target_user_id BIGINT NOT NULL,
    action_by_user_id BIGINT NOT NULL,
    action_type VARCHAR(40) NOT NULL,
    previous_account_status VARCHAR(40) NULL,
    new_account_status VARCHAR(40) NULL,
    reason VARCHAR(500) NOT NULL,
    suspension_ends_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_reporter_account_actions_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_reporter_account_actions_target_user
        FOREIGN KEY (target_user_id) REFERENCES users(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_reporter_account_actions_action_by
        FOREIGN KEY (action_by_user_id) REFERENCES users(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_reporter_account_actions_action_type CHECK (
        action_type IN ('warning', 'suspension', 'disable', 'reactivate', 'note')
    )
);
CREATE INDEX idx_reporter_account_actions_target_user ON reporter_account_actions (target_user_id);
CREATE INDEX idx_reporter_account_actions_action_by ON reporter_account_actions (action_by_user_id);
CREATE INDEX idx_reporter_account_actions_action_type ON reporter_account_actions (action_type);
CREATE INDEX idx_reporter_account_actions_created_at ON reporter_account_actions (created_at);

-- from 08_service_cases.sql
-- ============================================================
-- 4. Non-Emergency Service Cases
-- ============================================================



CREATE TABLE case_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_case_statuses_status_code UNIQUE (status_code)
);

CREATE TABLE case_status_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_status_id BIGINT NOT NULL,
    to_status_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_note BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id), CONSTRAINT uq_case_status_transitions_from_to UNIQUE (from_status_id, to_status_id),
    CONSTRAINT fk_case_status_transitions_from FOREIGN KEY (from_status_id) REFERENCES case_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_status_transitions_to FOREIGN KEY (to_status_id) REFERENCES case_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_case_status_transitions_to ON case_status_transitions (to_status_id);

CREATE TABLE service_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    case_code VARCHAR(60) NOT NULL,
    intake_report_id BIGINT NOT NULL,
    reporter_user_id BIGINT NOT NULL,
    parent_case_id BIGINT NULL,
    category_id BIGINT NOT NULL,
    current_status_id BIGINT NOT NULL,
    current_location_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    priority_level VARCHAR(64) CHECK (priority_level IN ('low','medium','high','urgent')) NOT NULL DEFAULT 'medium',
    source_channel_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_service_cases_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_service_cases_case_code UNIQUE (case_code), CONSTRAINT uq_service_cases_intake_report UNIQUE (intake_report_id),
    CONSTRAINT fk_service_cases_intake_report FOREIGN KEY (intake_report_id) REFERENCES intake_reports(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_service_cases_reporter FOREIGN KEY (reporter_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_service_cases_parent FOREIGN KEY (parent_case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_service_cases_category FOREIGN KEY (category_id) REFERENCES report_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_service_cases_status FOREIGN KEY (current_status_id) REFERENCES case_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_service_cases_location FOREIGN KEY (current_location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_service_cases_channel FOREIGN KEY (source_channel_id) REFERENCES report_channels(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_service_cases_title_not_blank CHECK (CHAR_LENGTH(TRIM(title)) > 0)
);
CREATE INDEX idx_service_cases_reporter ON service_cases (reporter_user_id);
CREATE INDEX idx_service_cases_parent ON service_cases (parent_case_id);
CREATE INDEX idx_service_cases_category ON service_cases (category_id);
CREATE INDEX idx_service_cases_status ON service_cases (current_status_id);
CREATE INDEX idx_service_cases_location ON service_cases (current_location_id);
CREATE INDEX idx_service_cases_priority ON service_cases (priority_level);
CREATE INDEX idx_service_cases_created_at ON service_cases (created_at);

CREATE TABLE case_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_case_status_history_case FOREIGN KEY (case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_status_history_status FOREIGN KEY (status_id) REFERENCES case_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_status_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_case_status_history_case_changed ON case_status_history (case_id, changed_at);
CREATE INDEX idx_case_status_history_status ON case_status_history (status_id);
CREATE INDEX idx_case_status_history_user ON case_status_history (changed_by_user_id);

CREATE TABLE case_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id BIGINT NOT NULL,
    assigned_admin_id BIGINT NOT NULL,
    assigned_by_user_id BIGINT NULL,
    assignment_status VARCHAR(64) CHECK (assignment_status IN ('active','completed','reassigned','cancelled')) NOT NULL DEFAULT 'active',
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP NULL,
    note VARCHAR(500) NULL,
    active_case_id BIGINT GENERATED ALWAYS AS (CASE WHEN assignment_status = 'active' AND ended_at IS NULL THEN case_id ELSE NULL END) STORED,
    PRIMARY KEY (id), CONSTRAINT uq_case_assignments_one_active UNIQUE (active_case_id),
    CONSTRAINT fk_case_assignments_case FOREIGN KEY (case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_assignments_admin FOREIGN KEY (assigned_admin_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_assignments_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_case_assignments_end_after_assigned CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);
CREATE INDEX idx_case_assignments_case ON case_assignments (case_id);
CREATE INDEX idx_case_assignments_admin ON case_assignments (assigned_admin_id);
CREATE INDEX idx_case_assignments_assigned_by ON case_assignments (assigned_by_user_id);

CREATE TABLE case_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id BIGINT NOT NULL,
    sender_user_id BIGINT NULL,
    message_type VARCHAR(64) CHECK (message_type IN ('user_message','admin_reply','system_note')) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NULL,
    is_internal BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_case_messages_case FOREIGN KEY (case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_messages_sender FOREIGN KEY (sender_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_case_messages_subject_not_blank CHECK (CHAR_LENGTH(TRIM(subject)) > 0)
);
CREATE INDEX idx_case_messages_case_created ON case_messages (case_id, created_at);
CREATE INDEX idx_case_messages_sender ON case_messages (sender_user_id);

CREATE TABLE case_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id BIGINT NOT NULL,
    message_id BIGINT NULL,
    uploaded_by_user_id BIGINT NULL,
    file_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    mime_type VARCHAR(120) NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_case_attachments_case FOREIGN KEY (case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_attachments_message FOREIGN KEY (message_id) REFERENCES case_messages(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_attachments_user FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_case_attachments_storage_key_not_blank CHECK (CHAR_LENGTH(TRIM(storage_key)) > 0)
);
CREATE INDEX idx_case_attachments_case ON case_attachments (case_id);
CREATE INDEX idx_case_attachments_message ON case_attachments (message_id);
CREATE INDEX idx_case_attachments_user ON case_attachments (uploaded_by_user_id);

CREATE TABLE case_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating SMALLINT NOT NULL,
    comment VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_case_feedback_case_user UNIQUE (case_id, user_id),
    CONSTRAINT fk_case_feedback_case FOREIGN KEY (case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_feedback_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_case_feedback_rating CHECK (rating BETWEEN 1 AND 5)
);
CREATE INDEX idx_case_feedback_user ON case_feedback (user_id);

-- from 09_agencies_and_units.sql
-- ============================================================
-- 5. Agencies and Units lookup foundations
-- ============================================================



CREATE TABLE agency_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_agency_types_type_code UNIQUE (type_code)
);

CREATE TABLE agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    agency_type_id BIGINT NOT NULL,
    agency_code VARCHAR(80) NOT NULL,
    name VARCHAR(180) NOT NULL,
    description VARCHAR(1000) NULL,
    head_office_location_id BIGINT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_agencies_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_agencies_agency_code UNIQUE (agency_code),
    CONSTRAINT fk_agencies_type FOREIGN KEY (agency_type_id) REFERENCES agency_types(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_agencies_head_office_location FOREIGN KEY (head_office_location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_agencies_name_not_blank CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);
CREATE INDEX idx_agencies_type ON agencies (agency_type_id);
CREATE INDEX idx_agencies_head_office_location ON agencies (head_office_location_id);

CREATE TABLE agency_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agency_id BIGINT NOT NULL,
    contact_type VARCHAR(64) CHECK (contact_type IN ('phone','email','hotline','fax','website')) NOT NULL,
    contact_value VARCHAR(255) NOT NULL,
    label VARCHAR(120) NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_agency_contacts_unique_value UNIQUE (agency_id, contact_type, contact_value),
    CONSTRAINT fk_agency_contacts_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_agency_contacts_value_not_blank CHECK (CHAR_LENGTH(TRIM(contact_value)) > 0)
);
CREATE INDEX idx_agency_contacts_agency ON agency_contacts (agency_id);

CREATE TABLE agency_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    agency_id BIGINT NOT NULL,
    membership_role VARCHAR(64) CHECK (membership_role IN ('representative','coordinator','operator','viewer')) NOT NULL,
    membership_status VARCHAR(64) CHECK (membership_status IN ('active','inactive','suspended','left')) NOT NULL DEFAULT 'active',
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_agency_memberships_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_agency_memberships_user_agency UNIQUE (user_id, agency_id),
    CONSTRAINT fk_agency_memberships_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_agency_memberships_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_agency_memberships_left_after_joined CHECK (left_at IS NULL OR left_at >= joined_at)
);
CREATE INDEX idx_agency_memberships_agency ON agency_memberships (agency_id);
CREATE INDEX idx_agency_memberships_role ON agency_memberships (membership_role);

CREATE TABLE capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    capability_code VARCHAR(120) NOT NULL,
    name VARCHAR(150) NOT NULL,
    capability_group VARCHAR(64) CHECK (capability_group IN ('medical','fire','rescue','relief','infrastructure','security','shelter','blood','other')) NOT NULL DEFAULT 'other',
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_capabilities_code UNIQUE (capability_code)
);
CREATE INDEX idx_capabilities_group ON capabilities (capability_group);

CREATE TABLE agency_capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agency_id BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,
    capacity_note VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_agency_capabilities_agency_capability UNIQUE (agency_id, capability_id),
    CONSTRAINT fk_agency_capabilities_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_agency_capabilities_capability FOREIGN KEY (capability_id) REFERENCES capabilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_agency_capabilities_capability ON agency_capabilities (capability_id);

CREATE TABLE agency_service_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agency_id BIGINT NOT NULL,
    admin_area_id BIGINT NOT NULL,
    coverage_type VARCHAR(64) CHECK (coverage_type IN ('primary','secondary','emergency_only')) NOT NULL DEFAULT 'primary',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_agency_service_areas_agency_area UNIQUE (agency_id, admin_area_id),
    CONSTRAINT fk_agency_service_areas_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_agency_service_areas_area FOREIGN KEY (admin_area_id) REFERENCES administrative_areas(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_agency_service_areas_area ON agency_service_areas (admin_area_id);

CREATE TABLE emergency_unit_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_emergency_unit_types_code UNIQUE (type_code)
);

CREATE TABLE unit_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_unit_statuses_status_code UNIQUE (status_code)
);

CREATE TABLE unit_status_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_status_id BIGINT NOT NULL,
    to_status_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_note BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id), CONSTRAINT uq_unit_status_transitions_from_to UNIQUE (from_status_id, to_status_id),
    CONSTRAINT fk_unit_status_transitions_from FOREIGN KEY (from_status_id) REFERENCES unit_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_unit_status_transitions_to FOREIGN KEY (to_status_id) REFERENCES unit_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_unit_status_transitions_to ON unit_status_transitions (to_status_id);

CREATE TABLE emergency_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    agency_id BIGINT NOT NULL,
    unit_type_id BIGINT NOT NULL,
    unit_code VARCHAR(80) NOT NULL,
    unit_name VARCHAR(150) NOT NULL,
    base_location_id BIGINT NOT NULL,
    current_status_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_emergency_units_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_emergency_units_agency_unit_code UNIQUE (agency_id, unit_code),
    CONSTRAINT fk_emergency_units_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_emergency_units_type FOREIGN KEY (unit_type_id) REFERENCES emergency_unit_types(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_emergency_units_base_location FOREIGN KEY (base_location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_emergency_units_current_status FOREIGN KEY (current_status_id) REFERENCES unit_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_emergency_units_code_not_blank CHECK (CHAR_LENGTH(TRIM(unit_code)) > 0),
    CONSTRAINT chk_emergency_units_name_not_blank CHECK (CHAR_LENGTH(TRIM(unit_name)) > 0)
);
CREATE INDEX idx_emergency_units_agency_status ON emergency_units (agency_id, current_status_id);
CREATE INDEX idx_emergency_units_current_status ON emergency_units (current_status_id);
CREATE INDEX idx_emergency_units_type ON emergency_units (unit_type_id);
CREATE INDEX idx_emergency_units_base_location ON emergency_units (base_location_id);

CREATE TABLE unit_capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_id BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_unit_capabilities_unit_capability UNIQUE (unit_id, capability_id),
    CONSTRAINT fk_unit_capabilities_unit FOREIGN KEY (unit_id) REFERENCES emergency_units(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_unit_capabilities_capability FOREIGN KEY (capability_id) REFERENCES capabilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_unit_capabilities_capability ON unit_capabilities (capability_id);

CREATE TABLE unit_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unit_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_unit_status_history_unit FOREIGN KEY (unit_id) REFERENCES emergency_units(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_unit_status_history_status FOREIGN KEY (status_id) REFERENCES unit_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_unit_status_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_unit_status_history_unit_changed ON unit_status_history (unit_id, changed_at);
CREATE INDEX idx_unit_status_history_status ON unit_status_history (status_id);
CREATE INDEX idx_unit_status_history_user ON unit_status_history (changed_by_user_id);

-- from 10_emergency_incidents.sql
-- ============================================================
-- 6. Emergency Incident Operations
-- ============================================================



CREATE TABLE incident_severity_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    severity_code VARCHAR(80) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL,
    priority_rank INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_incident_severity_levels_code UNIQUE (severity_code), CONSTRAINT uq_incident_severity_levels_rank UNIQUE (priority_rank)
);

CREATE TABLE incident_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_incident_statuses_code UNIQUE (status_code)
);

CREATE TABLE incident_status_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_status_id BIGINT NOT NULL,
    to_status_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_note BOOLEAN NOT NULL DEFAULT FALSE,
    requires_outcome BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id), CONSTRAINT uq_incident_status_transitions_from_to UNIQUE (from_status_id, to_status_id),
    CONSTRAINT fk_incident_status_transitions_from FOREIGN KEY (from_status_id) REFERENCES incident_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_status_transitions_to FOREIGN KEY (to_status_id) REFERENCES incident_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_incident_status_transitions_to ON incident_status_transitions (to_status_id);

CREATE TABLE incident_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    outcome_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    is_successful_resolution BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_incident_outcomes_code UNIQUE (outcome_code)
);

CREATE TABLE emergency_incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    incident_code VARCHAR(60) NOT NULL,
    category_id BIGINT NOT NULL,
    severity_level_id BIGINT NOT NULL,
    current_status_id BIGINT NOT NULL,
    current_location_id BIGINT NOT NULL,
    final_outcome_id BIGINT NULL,
    origin_type VARCHAR(64) CHECK (origin_type IN ('emergency_call','service_case_escalation','admin_created','agency_report','disaster_event')) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    created_by_user_id BIGINT NOT NULL,
    reported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL,
    closed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_emergency_incidents_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_emergency_incidents_incident_code UNIQUE (incident_code),
    CONSTRAINT fk_emergency_incidents_category FOREIGN KEY (category_id) REFERENCES report_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_emergency_incidents_severity FOREIGN KEY (severity_level_id) REFERENCES incident_severity_levels(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_emergency_incidents_status FOREIGN KEY (current_status_id) REFERENCES incident_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_emergency_incidents_location FOREIGN KEY (current_location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_emergency_incidents_outcome FOREIGN KEY (final_outcome_id) REFERENCES incident_outcomes(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_emergency_incidents_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_emergency_incidents_title_not_blank CHECK (CHAR_LENGTH(TRIM(title)) > 0),
    CONSTRAINT chk_emergency_incidents_reported_before_created CHECK (reported_at <= created_at),
    CONSTRAINT chk_emergency_incidents_resolved_after_report CHECK (resolved_at IS NULL OR resolved_at >= reported_at),
    CONSTRAINT chk_emergency_incidents_closed_after_report CHECK (closed_at IS NULL OR closed_at >= reported_at)
);
CREATE INDEX idx_emergency_incidents_category ON emergency_incidents (category_id);
CREATE INDEX idx_emergency_incidents_severity ON emergency_incidents (severity_level_id);
CREATE INDEX idx_emergency_incidents_status ON emergency_incidents (current_status_id);
CREATE INDEX idx_emergency_incidents_location ON emergency_incidents (current_location_id);
CREATE INDEX idx_emergency_incidents_outcome ON emergency_incidents (final_outcome_id);
CREATE INDEX idx_emergency_incidents_origin ON emergency_incidents (origin_type);
CREATE INDEX idx_emergency_incidents_reported_at ON emergency_incidents (reported_at);

CREATE TABLE incident_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    incident_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    outcome_id BIGINT NULL,
    changed_by_user_id BIGINT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_incident_status_history_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_status_history_status FOREIGN KEY (status_id) REFERENCES incident_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_status_history_outcome FOREIGN KEY (outcome_id) REFERENCES incident_outcomes(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_status_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_incident_status_history_incident_changed ON incident_status_history (incident_id, changed_at);
CREATE INDEX idx_incident_status_history_status ON incident_status_history (status_id);
CREATE INDEX idx_incident_status_history_outcome ON incident_status_history (outcome_id);
CREATE INDEX idx_incident_status_history_user ON incident_status_history (changed_by_user_id);

CREATE TABLE incident_report_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    incident_id BIGINT NOT NULL,
    intake_report_id BIGINT NOT NULL,
    link_type VARCHAR(64) CHECK (link_type IN ('primary_report','duplicate_report','supporting_report','follow_up_report')) NOT NULL,
    linked_by_user_id BIGINT NULL,
    linked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    unlinked_at TIMESTAMP NULL,
    unlinked_by_user_id BIGINT NULL,
    unlink_reason VARCHAR(500) NULL,
    active_incident_report_incident_id BIGINT GENERATED ALWAYS AS (CASE WHEN unlinked_at IS NULL THEN incident_id ELSE NULL END) STORED,
    active_incident_report_intake_id BIGINT GENERATED ALWAYS AS (CASE WHEN unlinked_at IS NULL THEN intake_report_id ELSE NULL END) STORED,
    active_intake_report_id BIGINT GENERATED ALWAYS AS (CASE WHEN unlinked_at IS NULL THEN intake_report_id ELSE NULL END) STORED,
    PRIMARY KEY (id), CONSTRAINT uq_incident_report_links_active_incident_report UNIQUE (active_incident_report_incident_id, active_incident_report_intake_id), CONSTRAINT uq_incident_report_links_active_one_incident_per_report UNIQUE (active_intake_report_id),
    CONSTRAINT fk_incident_report_links_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_report_links_report FOREIGN KEY (intake_report_id) REFERENCES intake_reports(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_report_links_user FOREIGN KEY (linked_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_report_links_unlinked_by_user FOREIGN KEY (unlinked_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_incident_report_links_unlink_reason_when_unlinked CHECK (
        unlinked_at IS NULL OR (unlink_reason IS NOT NULL AND CHAR_LENGTH(TRIM(unlink_reason)) > 0)
    )
);
CREATE INDEX idx_incident_report_links_user ON incident_report_links (linked_by_user_id);
CREATE INDEX idx_incident_report_links_unlinked_by_user ON incident_report_links (unlinked_by_user_id);

CREATE TABLE incident_agency_participation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    incident_id BIGINT NOT NULL,
    agency_id BIGINT NOT NULL,
    is_lead_agency BOOLEAN NOT NULL DEFAULT FALSE,
    participation_status VARCHAR(64) CHECK (participation_status IN ('requested','active','completed','withdrawn')) NOT NULL DEFAULT 'active',
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMP NULL,
    assigned_by_user_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lead_incident_id BIGINT GENERATED ALWAYS AS (CASE WHEN is_lead_agency THEN incident_id ELSE NULL END) STORED,
    PRIMARY KEY (id), CONSTRAINT uq_iap_incident_agency UNIQUE (incident_id, agency_id), CONSTRAINT uq_iap_one_lead_per_incident UNIQUE (lead_incident_id),
    CONSTRAINT fk_iap_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_iap_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_iap_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_iap_left_after_joined CHECK (left_at IS NULL OR left_at >= joined_at)
);
CREATE INDEX idx_iap_agency ON incident_agency_participation (agency_id);
CREATE INDEX idx_iap_assigned_by ON incident_agency_participation (assigned_by_user_id);
CREATE INDEX idx_iap_status ON incident_agency_participation (participation_status);

CREATE TABLE incident_location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    incident_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NULL,
    change_reason VARCHAR(500) NULL,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    current_incident_id BIGINT GENERATED ALWAYS AS (CASE WHEN is_current THEN incident_id ELSE NULL END) STORED,
    PRIMARY KEY (id), CONSTRAINT uq_incident_location_history_one_current UNIQUE (current_incident_id),
    CONSTRAINT fk_incident_location_history_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_location_history_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_location_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_incident_location_history_incident_changed ON incident_location_history (incident_id, changed_at);
CREATE INDEX idx_incident_location_history_location ON incident_location_history (location_id);
CREATE INDEX idx_incident_location_history_user ON incident_location_history (changed_by_user_id);

CREATE TABLE incident_timeline_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    incident_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_title VARCHAR(255) NOT NULL,
    event_description TEXT NULL,
    created_by_user_id BIGINT NULL,
    event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_incident_timeline_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_timeline_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_incident_timeline_title_not_blank CHECK (CHAR_LENGTH(TRIM(event_title)) > 0)
);
CREATE INDEX idx_incident_timeline_incident_time ON incident_timeline_events (incident_id, event_time);
CREATE INDEX idx_incident_timeline_user ON incident_timeline_events (created_by_user_id);
CREATE INDEX idx_incident_timeline_event_type ON incident_timeline_events (event_type);

-- from 11_dispatch_and_response.sql
-- ============================================================
-- 7. Dispatch and Response
-- ============================================================



CREATE TABLE dispatch_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_dispatch_statuses_status_code UNIQUE (status_code)
);

CREATE TABLE dispatch_status_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_status_id BIGINT NOT NULL,
    to_status_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_note BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id), CONSTRAINT uq_dispatch_status_transitions_from_to UNIQUE (from_status_id, to_status_id),
    CONSTRAINT fk_dispatch_status_transitions_from FOREIGN KEY (from_status_id) REFERENCES dispatch_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_dispatch_status_transitions_to FOREIGN KEY (to_status_id) REFERENCES dispatch_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_dispatch_status_transitions_to ON dispatch_status_transitions (to_status_id);

CREATE TABLE dispatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    incident_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    assigned_by_user_id BIGINT NOT NULL,
    current_status_id BIGINT NOT NULL,
    priority_level VARCHAR(64) CHECK (priority_level IN ('low','medium','high','critical')) NOT NULL DEFAULT 'medium',
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispatched_at TIMESTAMP NULL,
    arrived_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    cancellation_reason VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_dispatches_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_dispatches_incident_unit UNIQUE (incident_id, unit_id),
    CONSTRAINT fk_dispatches_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_dispatches_unit FOREIGN KEY (unit_id) REFERENCES emergency_units(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_dispatches_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_dispatches_current_status FOREIGN KEY (current_status_id) REFERENCES dispatch_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_dispatches_dispatched_after_assigned CHECK (dispatched_at IS NULL OR dispatched_at >= assigned_at),
    CONSTRAINT chk_dispatches_arrived_after_dispatched CHECK (arrived_at IS NULL OR (dispatched_at IS NOT NULL AND arrived_at >= dispatched_at)),
    CONSTRAINT chk_dispatches_completed_after_arrived CHECK (completed_at IS NULL OR (arrived_at IS NOT NULL AND completed_at >= arrived_at)),
    CONSTRAINT chk_dispatches_cancelled_after_assigned CHECK (cancelled_at IS NULL OR cancelled_at >= assigned_at)
);
CREATE INDEX idx_dispatches_unit ON dispatches (unit_id);
CREATE INDEX idx_dispatches_user ON dispatches (assigned_by_user_id);
CREATE INDEX idx_dispatches_status ON dispatches (current_status_id);
CREATE INDEX idx_dispatches_incident_status ON dispatches (incident_id, current_status_id);

CREATE TABLE dispatch_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dispatch_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_dispatch_status_history_dispatch FOREIGN KEY (dispatch_id) REFERENCES dispatches(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_dispatch_status_history_status FOREIGN KEY (status_id) REFERENCES dispatch_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_dispatch_status_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_dispatch_status_history_dispatch_changed ON dispatch_status_history (dispatch_id, changed_at);
CREATE INDEX idx_dispatch_status_history_status ON dispatch_status_history (status_id);
CREATE INDEX idx_dispatch_status_history_user ON dispatch_status_history (changed_by_user_id);

CREATE TABLE response_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    incident_id BIGINT NOT NULL,
    dispatch_id BIGINT NULL,
    agency_id BIGINT NOT NULL,
    created_by_user_id BIGINT NULL,
    log_type VARCHAR(64) CHECK (log_type IN ('update','hazard','casualty','resource_need','completion_note')) NOT NULL DEFAULT 'update',
    message TEXT NOT NULL,
    logged_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_response_logs_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_response_logs_dispatch FOREIGN KEY (dispatch_id) REFERENCES dispatches(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_response_logs_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_response_logs_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_response_logs_message_not_blank CHECK (CHAR_LENGTH(TRIM(message)) > 0)
);
CREATE INDEX idx_response_logs_incident_logged ON response_logs (incident_id, logged_at);
CREATE INDEX idx_response_logs_dispatch ON response_logs (dispatch_id);
CREATE INDEX idx_response_logs_agency ON response_logs (agency_id);
CREATE INDEX idx_response_logs_user ON response_logs (created_by_user_id);

-- from 12_operator_workload.sql
-- ============================================================
-- 8. Operator Workload Balancing
-- ============================================================



CREATE TABLE operator_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    shift_role VARCHAR(64) CHECK (shift_role IN ('case_admin','dispatcher','disaster_coordinator')) NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    shift_status VARCHAR(64) CHECK (shift_status IN ('scheduled','active','completed','cancelled')) NOT NULL DEFAULT 'scheduled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_operator_shifts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_operator_shifts_end_after_start CHECK (ends_at > starts_at)
);
CREATE INDEX idx_operator_shifts_user_time ON operator_shifts (user_id, starts_at, ends_at);
CREATE INDEX idx_operator_shifts_role_status ON operator_shifts (shift_role, shift_status);

CREATE TABLE operator_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    availability_status VARCHAR(64) CHECK (availability_status IN ('available','busy','offline','on_break')) NOT NULL,
    status_reason VARCHAR(500) NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_operator_availability_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_operator_availability_user_changed ON operator_availability (user_id, changed_at);
CREATE INDEX idx_operator_availability_status ON operator_availability (availability_status);

CREATE TABLE work_queues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    queue_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    queue_type VARCHAR(64) CHECK (queue_type IN ('service_case','emergency_call','dispatch','disaster_relief')) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_work_queues_queue_code UNIQUE (queue_code)
);

CREATE TABLE queue_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    queue_id BIGINT NOT NULL,
    entity_type VARCHAR(64) CHECK (entity_type IN ('service_case','intake_report','emergency_call','emergency_incident','relief_request')) NOT NULL,
    entity_id BIGINT NOT NULL,
    priority_level VARCHAR(64) CHECK (priority_level IN ('low','medium','high','critical')) NOT NULL DEFAULT 'medium',
    queue_status VARCHAR(64) CHECK (queue_status IN ('waiting','assigned','in_progress','completed','cancelled')) NOT NULL DEFAULT 'waiting',
    available_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_queue_items_queue FOREIGN KEY (queue_id) REFERENCES work_queues(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_queue_items_queue_status_priority ON queue_items (queue_id, queue_status, priority_level);
CREATE INDEX idx_queue_items_entity ON queue_items (entity_type, entity_id);

CREATE TABLE queue_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    queue_item_id BIGINT NOT NULL,
    assigned_to_user_id BIGINT NOT NULL,
    assigned_by_user_id BIGINT NULL,
    assignment_status VARCHAR(64) CHECK (assignment_status IN ('assigned','accepted','completed','reassigned','expired','cancelled')) NOT NULL DEFAULT 'assigned',
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accepted_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    ended_at TIMESTAMP NULL,
    active_queue_item_id BIGINT GENERATED ALWAYS AS (CASE WHEN ended_at IS NULL AND assignment_status IN ('assigned','accepted') THEN queue_item_id ELSE NULL END) STORED,
    PRIMARY KEY (id), CONSTRAINT uq_queue_assignments_one_active UNIQUE (active_queue_item_id),
    CONSTRAINT fk_queue_assignments_item FOREIGN KEY (queue_item_id) REFERENCES queue_items(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_queue_assignments_assigned_to FOREIGN KEY (assigned_to_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_queue_assignments_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_queue_assignments_accept_after_assigned CHECK (accepted_at IS NULL OR accepted_at >= assigned_at),
    CONSTRAINT chk_queue_assignments_complete_after_assigned CHECK (completed_at IS NULL OR completed_at >= assigned_at),
    CONSTRAINT chk_queue_assignments_end_after_assigned CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);
CREATE INDEX idx_queue_assignments_item ON queue_assignments (queue_item_id);
CREATE INDEX idx_queue_assignments_assigned_to ON queue_assignments (assigned_to_user_id);
CREATE INDEX idx_queue_assignments_assigned_by ON queue_assignments (assigned_by_user_id);

-- from 13_disaster_management.sql
-- ============================================================
-- 9. Disaster / National Emergency Management (BCNF)
-- ============================================================



CREATE TABLE disaster_event_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_disaster_event_types_code UNIQUE (type_code)
);

CREATE TABLE disaster_event_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_disaster_event_statuses_code UNIQUE (status_code)
);

CREATE TABLE disaster_event_status_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_status_id BIGINT NOT NULL,
    to_status_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_note BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id), CONSTRAINT uq_disaster_event_status_transitions_from_to UNIQUE (from_status_id, to_status_id),
    CONSTRAINT fk_dest_trans_from FOREIGN KEY (from_status_id) REFERENCES disaster_event_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_dest_trans_to FOREIGN KEY (to_status_id) REFERENCES disaster_event_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_disaster_event_status_transitions_to ON disaster_event_status_transitions (to_status_id);

CREATE TABLE disaster_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    event_code VARCHAR(60) NOT NULL,
    event_type_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    public_guidance TEXT NULL,
    current_status_id BIGINT NOT NULL,
    severity_level VARCHAR(64) CHECK (severity_level IN ('low','medium','high','critical','national')) NOT NULL DEFAULT 'medium',
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_disaster_events_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_disaster_events_event_code UNIQUE (event_code),
    CONSTRAINT fk_disaster_events_type FOREIGN KEY (event_type_id) REFERENCES disaster_event_types(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_events_status FOREIGN KEY (current_status_id) REFERENCES disaster_event_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_events_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_disaster_events_title_not_blank CHECK (CHAR_LENGTH(TRIM(title)) > 0),
    CONSTRAINT chk_disaster_events_end_after_start CHECK (ended_at IS NULL OR ended_at >= started_at)
);
CREATE INDEX idx_disaster_events_type ON disaster_events (event_type_id);
CREATE INDEX idx_disaster_events_status ON disaster_events (current_status_id);
CREATE INDEX idx_disaster_events_started ON disaster_events (started_at);

CREATE TABLE disaster_event_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    disaster_event_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_desh_event FOREIGN KEY (disaster_event_id) REFERENCES disaster_events(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_desh_status FOREIGN KEY (status_id) REFERENCES disaster_event_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_desh_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_desh_event_changed ON disaster_event_status_history (disaster_event_id, changed_at);
CREATE INDEX idx_desh_status ON disaster_event_status_history (status_id);
CREATE INDEX idx_desh_user ON disaster_event_status_history (changed_by_user_id);

CREATE TABLE disaster_affected_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    disaster_event_id BIGINT NOT NULL,
    admin_area_id BIGINT NOT NULL,
    added_by_user_id BIGINT NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_disaster_affected_areas_event_area UNIQUE (disaster_event_id, admin_area_id), CONSTRAINT uq_disaster_affected_areas_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_disaster_affected_areas_event FOREIGN KEY (disaster_event_id) REFERENCES disaster_events(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_affected_areas_area FOREIGN KEY (admin_area_id) REFERENCES administrative_areas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_affected_areas_user FOREIGN KEY (added_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_disaster_affected_areas_area ON disaster_affected_areas (admin_area_id);

CREATE TABLE disaster_affected_area_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    disaster_affected_area_id BIGINT NOT NULL,
    impact_level VARCHAR(64) CHECK (impact_level IN ('low','medium','high','severe')) NOT NULL DEFAULT 'medium',
    estimated_affected_people INTEGER NULL,
    shelter_support_required BOOLEAN NOT NULL DEFAULT FALSE,
    relief_support_required BOOLEAN NOT NULL DEFAULT FALSE,
    assessment_note VARCHAR(1000) NULL,
    recorded_by_user_id BIGINT NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_daaa_area FOREIGN KEY (disaster_affected_area_id) REFERENCES disaster_affected_areas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_daaa_user FOREIGN KEY (recorded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_daaa_area_recorded ON disaster_affected_area_assessments (disaster_affected_area_id, recorded_at);
CREATE INDEX idx_daaa_user ON disaster_affected_area_assessments (recorded_by_user_id);

CREATE TABLE disaster_agency_responsibilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    disaster_event_id BIGINT NOT NULL,
    agency_id BIGINT NOT NULL,
    responsibility_type VARCHAR(64) CHECK (responsibility_type IN (
        'coordination',
        'shelter_management',
        'relief_management',
        'medical_support',
        'security_support',
        'rescue_support'
    )) NOT NULL,
    is_lead BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_by_user_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deactivated_at TIMESTAMP NULL,
    PRIMARY KEY (id), CONSTRAINT uq_disaster_agency_resp_event_agency_type UNIQUE (disaster_event_id, agency_id, responsibility_type),
    CONSTRAINT fk_disaster_agency_resp_event FOREIGN KEY (disaster_event_id) REFERENCES disaster_events(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_agency_resp_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_agency_resp_user FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_disaster_agency_resp_agency ON disaster_agency_responsibilities (agency_id);
CREATE INDEX idx_disaster_agency_resp_type ON disaster_agency_responsibilities (disaster_event_id, responsibility_type);

CREATE TABLE disaster_declarations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    disaster_event_id BIGINT NOT NULL,
    declaration_code VARCHAR(80) NOT NULL,
    declaration_kind VARCHAR(64) CHECK (declaration_kind IN ('initial','amendment')) NOT NULL,
    title VARCHAR(255) NOT NULL,
    public_guidance TEXT NULL,
    legal_reference VARCHAR(255) NULL,
    reason VARCHAR(1000) NOT NULL,
    issued_by_user_id BIGINT NOT NULL,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    initial_disaster_event_id BIGINT GENERATED ALWAYS AS (
        CASE WHEN declaration_kind = 'initial' THEN disaster_event_id ELSE NULL END
    ) STORED,
    PRIMARY KEY (id), CONSTRAINT uq_disaster_declarations_code UNIQUE (declaration_code), CONSTRAINT uq_disaster_declarations_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_disaster_declarations_one_initial_per_disaster UNIQUE (initial_disaster_event_id),
    CONSTRAINT fk_disaster_declarations_disaster FOREIGN KEY (disaster_event_id) REFERENCES disaster_events(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_declarations_user FOREIGN KEY (issued_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_disaster_declarations_title_not_blank CHECK (CHAR_LENGTH(TRIM(title)) > 0),
    CONSTRAINT chk_disaster_declarations_reason_not_blank CHECK (CHAR_LENGTH(TRIM(reason)) > 0)
);
CREATE INDEX idx_disaster_declarations_disaster ON disaster_declarations (disaster_event_id);
CREATE INDEX idx_disaster_declarations_issued_by ON disaster_declarations (issued_by_user_id);
