CREATE TABLE disaster_incident_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    disaster_event_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    linked_by_user_id BIGINT NOT NULL,
    linked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    link_note VARCHAR(500) NULL,
    unlinked_at TIMESTAMP NULL,
    unlinked_by_user_id BIGINT NULL,
    unlink_reason VARCHAR(500) NULL,
    active_incident_id BIGINT GENERATED ALWAYS AS (
        CASE WHEN unlinked_at IS NULL THEN incident_id ELSE NULL END
    ) STORED,
    PRIMARY KEY (id), CONSTRAINT uq_disaster_incident_links_active_incident UNIQUE (active_incident_id),
    CONSTRAINT fk_disaster_incident_links_disaster FOREIGN KEY (disaster_event_id) REFERENCES disaster_events(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_incident_links_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_incident_links_linked_by FOREIGN KEY (linked_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_disaster_incident_links_unlinked_by FOREIGN KEY (unlinked_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_disaster_incident_links_unlink_reason CHECK (
        unlinked_at IS NULL OR (unlink_reason IS NOT NULL AND CHAR_LENGTH(TRIM(unlink_reason)) > 0)
    )
);
CREATE INDEX idx_disaster_incident_links_disaster ON disaster_incident_links (disaster_event_id);
CREATE INDEX idx_disaster_incident_links_incident ON disaster_incident_links (incident_id);

-- from 14_facilities_healthcare.sql
-- ============================================================
-- 10. Facilities and Healthcare
-- ============================================================



CREATE TABLE facility_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_facility_types_code UNIQUE (type_code)
);

CREATE TABLE facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    facility_type_id BIGINT NOT NULL,
    facility_code VARCHAR(80) NOT NULL,
    name VARCHAR(180) NOT NULL,
    location_id BIGINT NOT NULL,
    owning_agency_id BIGINT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_facilities_public_uuid UNIQUE (public_uuid), CONSTRAINT uq_facilities_facility_code UNIQUE (facility_code),
    CONSTRAINT fk_facilities_type FOREIGN KEY (facility_type_id) REFERENCES facility_types(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_facilities_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_facilities_agency FOREIGN KEY (owning_agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_facilities_name_not_blank CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);
CREATE INDEX idx_facilities_type ON facilities (facility_type_id);
CREATE INDEX idx_facilities_location ON facilities (location_id);
CREATE INDEX idx_facilities_agency ON facilities (owning_agency_id);

CREATE TABLE facility_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    facility_id BIGINT NOT NULL,
    contact_type VARCHAR(64) CHECK (contact_type IN ('phone','email','hotline','website')) NOT NULL,
    contact_value VARCHAR(255) NOT NULL,
    label VARCHAR(120) NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_facility_contacts_unique_value UNIQUE (facility_id, contact_type, contact_value),
    CONSTRAINT fk_facility_contacts_facility FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_facility_contacts_value_not_blank CHECK (CHAR_LENGTH(TRIM(contact_value)) > 0)
);

CREATE TABLE facility_capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    facility_id BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,
    capacity_note VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_facility_capabilities_facility_capability UNIQUE (facility_id, capability_id),
    CONSTRAINT fk_facility_capabilities_facility FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_facility_capabilities_capability FOREIGN KEY (capability_id) REFERENCES capabilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_facility_capabilities_capability ON facility_capabilities (capability_id);

CREATE TABLE facility_default_capacities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    facility_id BIGINT NOT NULL,
    capacity_type VARCHAR(64) CHECK (capacity_type IN ('shelter_people','hospital_beds','emergency_beds')) NOT NULL,
    total_capacity INTEGER NOT NULL,
    effective_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id), CONSTRAINT uq_facility_default_capacities_facility_type UNIQUE (facility_id, capacity_type),
    CONSTRAINT fk_facility_default_capacities_facility FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_facility_default_capacities_positive CHECK (total_capacity > 0)
);

CREATE TABLE facility_capacity_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    facility_id BIGINT NOT NULL,
    capacity_type VARCHAR(64) CHECK (capacity_type IN ('hospital_beds','emergency_beds','icu_beds')) NOT NULL,
    total_capacity INTEGER NOT NULL,
    occupied_capacity INTEGER NOT NULL DEFAULT 0,
    recorded_by_user_id BIGINT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_facility_capacity_facility FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_facility_capacity_user FOREIGN KEY (recorded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_facility_capacity_occupied_le_total CHECK (occupied_capacity <= total_capacity)
);
CREATE INDEX idx_facility_capacity_facility_type_recorded ON facility_capacity_snapshots (facility_id, capacity_type, recorded_at);
CREATE INDEX idx_facility_capacity_user ON facility_capacity_snapshots (recorded_by_user_id);

CREATE TABLE incident_facility_referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    incident_id BIGINT NOT NULL,
    facility_id BIGINT NOT NULL,
    referred_by_user_id BIGINT NOT NULL,
    referral_type VARCHAR(64) CHECK (referral_type IN ('hospital_transfer','shelter_referral','blood_bank_referral','relief_center')) NOT NULL,
    referral_status VARCHAR(64) CHECK (referral_status IN ('recommended','accepted','rejected','completed','cancelled')) NOT NULL DEFAULT 'recommended',
    reason VARCHAR(1000) NULL,
    referred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    PRIMARY KEY (id), CONSTRAINT uq_incident_facility_referrals_unique UNIQUE (incident_id, facility_id, referral_type),
    CONSTRAINT fk_incident_facility_referrals_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_facility_referrals_facility FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_incident_facility_referrals_user FOREIGN KEY (referred_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_incident_facility_referrals_completed_after_referred CHECK (completed_at IS NULL OR completed_at >= referred_at)
);
CREATE INDEX idx_incident_facility_referrals_facility ON incident_facility_referrals (facility_id);
CREATE INDEX idx_incident_facility_referrals_user ON incident_facility_referrals (referred_by_user_id);

CREATE TABLE shelter_activations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    disaster_event_id BIGINT NOT NULL,
    facility_id BIGINT NOT NULL,
    activated_by_user_id BIGINT NOT NULL,
    activation_status VARCHAR(64) CHECK (activation_status IN ('active','finalized')) NOT NULL DEFAULT 'active',
    activation_source VARCHAR(64) CHECK (activation_source IN ('auto','manual')) NOT NULL DEFAULT 'auto',
    manual_override_note VARCHAR(1000) NULL,
    usable_capacity_override INTEGER NULL,
    managing_agency_id BIGINT NULL,
    activated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at TIMESTAMP NULL,
    PRIMARY KEY (id), CONSTRAINT uq_shelter_activations_disaster_facility UNIQUE (disaster_event_id, facility_id), CONSTRAINT uq_shelter_activations_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_shelter_activations_disaster FOREIGN KEY (disaster_event_id) REFERENCES disaster_events(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_shelter_activations_facility FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_shelter_activations_user FOREIGN KEY (activated_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_shelter_activations_agency FOREIGN KEY (managing_agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_shelter_activations_finalized_after_activated CHECK (finalized_at IS NULL OR finalized_at >= activated_at)
);
CREATE INDEX idx_shelter_activations_facility ON shelter_activations (facility_id);
CREATE INDEX idx_shelter_activations_managing_agency ON shelter_activations (managing_agency_id);

CREATE TABLE relief_hub_activations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    disaster_event_id BIGINT NOT NULL,
    facility_id BIGINT NOT NULL,
    activated_by_user_id BIGINT NOT NULL,
    activation_status VARCHAR(64) CHECK (activation_status IN ('active','finalized')) NOT NULL DEFAULT 'active',
    activation_source VARCHAR(64) CHECK (activation_source IN ('auto','manual')) NOT NULL DEFAULT 'auto',
    manual_override_note VARCHAR(1000) NULL,
    managing_agency_id BIGINT NULL,
    activated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at TIMESTAMP NULL,
    PRIMARY KEY (id), CONSTRAINT uq_relief_hub_activations_disaster_facility UNIQUE (disaster_event_id, facility_id), CONSTRAINT uq_relief_hub_activations_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_relief_hub_activations_disaster FOREIGN KEY (disaster_event_id) REFERENCES disaster_events(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_hub_activations_facility FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_hub_activations_user FOREIGN KEY (activated_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_hub_activations_agency FOREIGN KEY (managing_agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_relief_hub_activations_finalized_after_activated CHECK (finalized_at IS NULL OR finalized_at >= activated_at)
);
CREATE INDEX idx_relief_hub_activations_facility ON relief_hub_activations (facility_id);
CREATE INDEX idx_relief_hub_activations_managing_agency ON relief_hub_activations (managing_agency_id);

CREATE TABLE shelter_occupancy_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shelter_activation_id BIGINT NOT NULL,
    people_count INTEGER NOT NULL DEFAULT 0,
    recorded_by_user_id BIGINT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_shelter_occupancy_activation FOREIGN KEY (shelter_activation_id) REFERENCES shelter_activations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_shelter_occupancy_user FOREIGN KEY (recorded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_shelter_occupancy_activation_recorded ON shelter_occupancy_snapshots (shelter_activation_id, recorded_at);
CREATE INDEX idx_shelter_occupancy_user ON shelter_occupancy_snapshots (recorded_by_user_id);

CREATE TABLE case_resolutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id BIGINT NOT NULL,
    resolved_by_user_id BIGINT NOT NULL,
    resolution_type VARCHAR(64) CHECK (resolution_type IN ('advice_given','referred_to_facility','escalated','no_action_needed','duplicate')) NOT NULL,
    resolution_text TEXT NOT NULL,
    recommended_facility_id BIGINT NULL,
    resolved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_case_resolutions_case UNIQUE (case_id),
    CONSTRAINT fk_case_resolutions_case FOREIGN KEY (case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_resolutions_user FOREIGN KEY (resolved_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_resolutions_facility FOREIGN KEY (recommended_facility_id) REFERENCES facilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_case_resolutions_text_not_blank CHECK (CHAR_LENGTH(TRIM(resolution_text)) > 0)
);
CREATE INDEX idx_case_resolutions_user ON case_resolutions (resolved_by_user_id);
CREATE INDEX idx_case_resolutions_facility ON case_resolutions (recommended_facility_id);

CREATE TABLE case_escalations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id BIGINT NOT NULL,
    emergency_incident_id BIGINT NOT NULL,
    escalated_by_user_id BIGINT NOT NULL,
    escalation_reason VARCHAR(1000) NOT NULL,
    escalated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_case_escalations_case UNIQUE (case_id), CONSTRAINT uq_case_escalations_case_incident UNIQUE (case_id, emergency_incident_id),
    CONSTRAINT fk_case_escalations_case FOREIGN KEY (case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_escalations_incident FOREIGN KEY (emergency_incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_case_escalations_user FOREIGN KEY (escalated_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_case_escalations_reason_not_blank CHECK (CHAR_LENGTH(TRIM(escalation_reason)) > 0)
);
CREATE INDEX idx_case_escalations_incident ON case_escalations (emergency_incident_id);
CREATE INDEX idx_case_escalations_user ON case_escalations (escalated_by_user_id);

-- from 15_relief.sql
-- ============================================================
-- 11. Relief Distribution (BCNF — facility/shelter scoped)
-- ============================================================



CREATE TABLE relief_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    unit_of_measure VARCHAR(50) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_relief_items_code UNIQUE (item_code)
);

CREATE TABLE relief_request_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_relief_request_statuses_code UNIQUE (status_code)
);

CREATE TABLE relief_request_status_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_status_id BIGINT NOT NULL,
    to_status_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_note BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id), CONSTRAINT uq_relief_request_status_transitions_from_to UNIQUE (from_status_id, to_status_id),
    CONSTRAINT fk_rrst_from FOREIGN KEY (from_status_id) REFERENCES relief_request_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_rrst_to FOREIGN KEY (to_status_id) REFERENCES relief_request_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_relief_request_status_transitions_to ON relief_request_status_transitions (to_status_id);

CREATE TABLE relief_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    request_code VARCHAR(80) NOT NULL,
    disaster_event_id BIGINT NOT NULL,
    shelter_activation_id BIGINT NOT NULL,
    current_status_id BIGINT NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    requesting_agency_id BIGINT NULL,
    request_note VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_relief_requests_code UNIQUE (request_code), CONSTRAINT uq_relief_requests_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_relief_requests_disaster FOREIGN KEY (disaster_event_id) REFERENCES disaster_events(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_requests_shelter FOREIGN KEY (shelter_activation_id) REFERENCES shelter_activations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_requests_status FOREIGN KEY (current_status_id) REFERENCES relief_request_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_requests_user FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_requests_agency FOREIGN KEY (requesting_agency_id) REFERENCES agencies(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_relief_requests_disaster ON relief_requests (disaster_event_id);
CREATE INDEX idx_relief_requests_shelter ON relief_requests (shelter_activation_id);
CREATE INDEX idx_relief_requests_status ON relief_requests (current_status_id);

CREATE TABLE relief_request_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    relief_request_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    changed_by_user_id BIGINT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_rrsh_request FOREIGN KEY (relief_request_id) REFERENCES relief_requests(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_rrsh_status FOREIGN KEY (status_id) REFERENCES relief_request_statuses(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_rrsh_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_rrsh_request_changed ON relief_request_status_history (relief_request_id, changed_at);
CREATE INDEX idx_rrsh_status ON relief_request_status_history (status_id);

CREATE TABLE relief_request_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    relief_request_id BIGINT NOT NULL,
    relief_item_id BIGINT NOT NULL,
    quantity_requested DECIMAL(12,2) NOT NULL,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id), CONSTRAINT uq_relief_request_items_request_item UNIQUE (relief_request_id, relief_item_id),
    CONSTRAINT fk_rri_request FOREIGN KEY (relief_request_id) REFERENCES relief_requests(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_rri_item FOREIGN KEY (relief_item_id) REFERENCES relief_items(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_rri_quantity_positive CHECK (quantity_requested > 0)
);
CREATE INDEX idx_relief_request_items_item ON relief_request_items (relief_item_id);

CREATE TABLE relief_stock_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    relief_hub_activation_id BIGINT NOT NULL,
    relief_item_id BIGINT NOT NULL,
    quantity_received DECIMAL(12,2) NOT NULL,
    received_by_user_id BIGINT NOT NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id), CONSTRAINT uq_relief_stock_receipts_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_relief_stock_receipts_hub FOREIGN KEY (relief_hub_activation_id) REFERENCES relief_hub_activations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_stock_receipts_item FOREIGN KEY (relief_item_id) REFERENCES relief_items(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_stock_receipts_user FOREIGN KEY (received_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_relief_stock_receipts_quantity_positive CHECK (quantity_received > 0)
);
CREATE INDEX idx_relief_stock_receipts_hub ON relief_stock_receipts (relief_hub_activation_id);
CREATE INDEX idx_relief_stock_receipts_item ON relief_stock_receipts (relief_item_id);

CREATE TABLE relief_distributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_uuid CHAR(36) NOT NULL,
    distribution_code VARCHAR(80) NOT NULL,
    relief_request_id BIGINT NOT NULL,
    source_hub_activation_id BIGINT NOT NULL,
    destination_shelter_activation_id BIGINT NOT NULL,
    distributed_by_user_id BIGINT NOT NULL,
    distributed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id), CONSTRAINT uq_relief_distributions_code UNIQUE (distribution_code), CONSTRAINT uq_relief_distributions_public_uuid UNIQUE (public_uuid),
    CONSTRAINT fk_relief_distributions_request FOREIGN KEY (relief_request_id) REFERENCES relief_requests(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_distributions_source FOREIGN KEY (source_hub_activation_id) REFERENCES relief_hub_activations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_distributions_destination FOREIGN KEY (destination_shelter_activation_id) REFERENCES shelter_activations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_relief_distributions_user FOREIGN KEY (distributed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_relief_distributions_request ON relief_distributions (relief_request_id);
CREATE INDEX idx_relief_distributions_source ON relief_distributions (source_hub_activation_id);
CREATE INDEX idx_relief_distributions_destination ON relief_distributions (destination_shelter_activation_id);

CREATE TABLE relief_distribution_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    relief_distribution_id BIGINT NOT NULL,
    relief_item_id BIGINT NOT NULL,
    quantity_delivered DECIMAL(12,2) NOT NULL,
    PRIMARY KEY (id), CONSTRAINT uq_relief_distribution_items_distribution_item UNIQUE (relief_distribution_id, relief_item_id),
    CONSTRAINT fk_rdi_distribution FOREIGN KEY (relief_distribution_id) REFERENCES relief_distributions(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_rdi_item FOREIGN KEY (relief_item_id) REFERENCES relief_items(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_rdi_quantity_positive CHECK (quantity_delivered > 0)
);
CREATE INDEX idx_relief_distribution_items_item ON relief_distribution_items (relief_item_id);

-- from 16_blood_support.sql
-- ============================================================
-- 12. Blood Support
-- ============================================================



CREATE TABLE blood_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_code VARCHAR(5) NOT NULL,
    name VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id), CONSTRAINT uq_blood_groups_code UNIQUE (group_code)
);

CREATE TABLE blood_donors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NULL,
    reporter_contact_id BIGINT NULL,
    blood_group_id BIGINT NOT NULL,
    preferred_location_id BIGINT NULL,
    consent_to_contact BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_blood_donors_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_blood_donors_contact FOREIGN KEY (reporter_contact_id) REFERENCES reporter_contacts(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_blood_donors_group FOREIGN KEY (blood_group_id) REFERENCES blood_groups(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_blood_donors_location FOREIGN KEY (preferred_location_id) REFERENCES locations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_blood_donors_has_identity CHECK (user_id IS NOT NULL OR reporter_contact_id IS NOT NULL)
);
CREATE INDEX idx_blood_donors_user ON blood_donors (user_id);
CREATE INDEX idx_blood_donors_contact ON blood_donors (reporter_contact_id);
CREATE INDEX idx_blood_donors_group ON blood_donors (blood_group_id);
CREATE INDEX idx_blood_donors_location ON blood_donors (preferred_location_id);

CREATE TABLE donor_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    blood_donor_id BIGINT NOT NULL,
    availability_status VARCHAR(64) CHECK (availability_status IN ('available','unavailable','temporarily_unavailable')) NOT NULL DEFAULT 'available',
    available_from TIMESTAMP NULL,
    available_until TIMESTAMP NULL,
    last_donated_at TIMESTAMP NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_donor_availability_donor FOREIGN KEY (blood_donor_id) REFERENCES blood_donors(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_donor_availability_until_after_from CHECK (available_until IS NULL OR available_from IS NULL OR available_until >= available_from)
);
CREATE INDEX idx_donor_availability_donor_updated ON donor_availability (blood_donor_id, updated_at);
CREATE INDEX idx_donor_availability_status ON donor_availability (availability_status);

CREATE TABLE blood_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_code VARCHAR(80) NOT NULL,
    incident_id BIGINT NULL,
    service_case_id BIGINT NULL,
    requesting_facility_id BIGINT NULL,
    blood_group_id BIGINT NOT NULL,
    units_required INTEGER NOT NULL,
    urgency_level VARCHAR(64) CHECK (urgency_level IN ('normal','urgent','critical')) NOT NULL DEFAULT 'normal',
    request_status VARCHAR(64) CHECK (request_status IN ('open','partially_matched','fulfilled','cancelled')) NOT NULL DEFAULT 'open',
    needed_by TIMESTAMP NULL,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_blood_requests_code UNIQUE (request_code),
    CONSTRAINT fk_blood_requests_incident FOREIGN KEY (incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_blood_requests_case FOREIGN KEY (service_case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_blood_requests_facility FOREIGN KEY (requesting_facility_id) REFERENCES facilities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_blood_requests_group FOREIGN KEY (blood_group_id) REFERENCES blood_groups(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_blood_requests_user FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_blood_requests_units_positive CHECK (units_required > 0)
);
CREATE INDEX idx_blood_requests_incident ON blood_requests (incident_id);
CREATE INDEX idx_blood_requests_case ON blood_requests (service_case_id);
CREATE INDEX idx_blood_requests_facility ON blood_requests (requesting_facility_id);
CREATE INDEX idx_blood_requests_group_status ON blood_requests (blood_group_id, request_status);

CREATE TABLE blood_request_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    blood_request_id BIGINT NOT NULL,
    blood_donor_id BIGINT NOT NULL,
    match_status VARCHAR(64) CHECK (match_status IN ('proposed','contacted','accepted','declined','donated','cancelled')) NOT NULL DEFAULT 'proposed',
    matched_by_user_id BIGINT NULL,
    matched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    contacted_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    note VARCHAR(500) NULL,
    PRIMARY KEY (id), CONSTRAINT uq_blood_matches_request_donor UNIQUE (blood_request_id, blood_donor_id),
    CONSTRAINT fk_blood_matches_request FOREIGN KEY (blood_request_id) REFERENCES blood_requests(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_blood_matches_donor FOREIGN KEY (blood_donor_id) REFERENCES blood_donors(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_blood_matches_user FOREIGN KEY (matched_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_blood_matches_contacted_after_matched CHECK (contacted_at IS NULL OR contacted_at >= matched_at),
    CONSTRAINT chk_blood_matches_completed_after_matched CHECK (completed_at IS NULL OR completed_at >= matched_at)
);
CREATE INDEX idx_blood_matches_donor ON blood_request_matches (blood_donor_id);
CREATE INDEX idx_blood_matches_user ON blood_request_matches (matched_by_user_id);

-- from 17_notifications_and_email.sql
-- ============================================================
-- 13. Notifications and Email
-- ============================================================



CREATE TABLE notification_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_code VARCHAR(120) NOT NULL,
    channel VARCHAR(64) CHECK (channel IN ('in_app','email')) NOT NULL,
    subject_template VARCHAR(255) NULL,
    body_template TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_notification_templates_code UNIQUE (template_code),
    CONSTRAINT chk_notification_templates_body_not_blank CHECK (CHAR_LENGTH(TRIM(body_template)) > 0)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_id BIGINT NULL,
    notification_type VARCHAR(64) CHECK (notification_type IN ('case_reply','case_resolved','case_escalated','incident_update','dispatch_update','relief_update','blood_request_update')) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    entity_type VARCHAR(100) NULL,
    entity_id BIGINT NULL,
    created_by_user_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_notifications_template FOREIGN KEY (template_id) REFERENCES notification_templates(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_notifications_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_notifications_title_not_blank CHECK (CHAR_LENGTH(TRIM(title)) > 0),
    CONSTRAINT chk_notifications_body_not_blank CHECK (CHAR_LENGTH(TRIM(body)) > 0)
);
CREATE INDEX idx_notifications_template ON notifications (template_id);
CREATE INDEX idx_notifications_entity ON notifications (entity_type, entity_id);
CREATE INDEX idx_notifications_created_by ON notifications (created_by_user_id);

CREATE TABLE notification_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notification_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    delivery_channel VARCHAR(64) CHECK (delivery_channel IN ('in_app','email')) NOT NULL,
    read_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_notification_recipients_unique UNIQUE (notification_id, recipient_user_id, delivery_channel),
    CONSTRAINT fk_notification_recipients_notification FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_notification_recipients_user FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX idx_notification_recipients_user_read ON notification_recipients (recipient_user_id, read_at);

CREATE TABLE email_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notification_id BIGINT NULL,
    recipient_user_id BIGINT NULL,
    to_email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    email_status VARCHAR(64) CHECK (email_status IN ('pending','sending','sent','failed','cancelled')) NOT NULL DEFAULT 'pending',
    available_to_send_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_email_outbox_notification FOREIGN KEY (notification_id) REFERENCES notifications(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_email_outbox_user FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_email_outbox_to_not_blank CHECK (CHAR_LENGTH(TRIM(to_email)) > 0),
    CONSTRAINT chk_email_outbox_subject_not_blank CHECK (CHAR_LENGTH(TRIM(subject)) > 0),
    CONSTRAINT chk_email_outbox_body_not_blank CHECK (CHAR_LENGTH(TRIM(body)) > 0)
);
CREATE INDEX idx_email_outbox_status_available ON email_outbox (email_status, available_to_send_at);
CREATE INDEX idx_email_outbox_notification ON email_outbox (notification_id);
CREATE INDEX idx_email_outbox_user ON email_outbox (recipient_user_id);

CREATE TABLE email_delivery_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email_outbox_id BIGINT NOT NULL,
    attempt_number INTEGER NOT NULL,
    attempt_status VARCHAR(64) CHECK (attempt_status IN ('success','failed')) NOT NULL,
    provider_response TEXT NULL,
    error_message TEXT NULL,
    attempted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id), CONSTRAINT uq_email_attempts_email_attempt UNIQUE (email_outbox_id, attempt_number),
    CONSTRAINT fk_email_attempts_outbox FOREIGN KEY (email_outbox_id) REFERENCES email_outbox(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_email_attempts_attempt_positive CHECK (attempt_number > 0)
);

-- from 18_audit.sql
-- ============================================================
-- 14. Audit
-- ============================================================



CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_user_id BIGINT NULL,
    action VARCHAR(120) NOT NULL,
    entity_type VARCHAR(120) NOT NULL,
    entity_id BIGINT NOT NULL,
    related_incident_id BIGINT NULL,
    related_case_id BIGINT NULL,
    related_disaster_event_id BIGINT NULL,
    details_json JSON NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_audit_related_incident FOREIGN KEY (related_incident_id) REFERENCES emergency_incidents(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_audit_related_case FOREIGN KEY (related_case_id) REFERENCES service_cases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_audit_related_disaster FOREIGN KEY (related_disaster_event_id) REFERENCES disaster_events(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_audit_action_not_blank CHECK (CHAR_LENGTH(TRIM(action)) > 0),
    CONSTRAINT chk_audit_entity_type_not_blank CHECK (CHAR_LENGTH(TRIM(entity_type)) > 0),
    CONSTRAINT chk_audit_details_json_valid CHECK (details_json IS NULL OR details_json IS NOT NULL)
);
CREATE INDEX idx_audit_actor_created ON audit_logs (actor_user_id, created_at);
CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_related_incident ON audit_logs (related_incident_id);
CREATE INDEX idx_audit_related_case ON audit_logs (related_case_id);
CREATE INDEX idx_audit_related_disaster ON audit_logs (related_disaster_event_id);
CREATE INDEX idx_audit_action ON audit_logs (action);

-- from 27_alter (no-op)
-- Skipped dynamic MySQL migration from 27_alter_agency_memberships_public_uuid.sql
-- Fresh installs already include agency_memberships.public_uuid in 09_agencies_and_units.sql
